server:
  port: 8082

# database
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.100:3306/mall-oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  # primary key auto increment
